#!/bin/bash
echo "Install CUPS (Common Unix Printing System)"
echo "Press \"y\" to install CUPS, or any key to abort"
read -n1 a
a=`echo $a | tr '[A-Z]' '[a-z]'`
if [ "$a" = "y" ]; then
    echo ""
     sudo apt-get install -y cups cups-pdf system-config-printer printer-driver-hpijs
     x-www-browser http://localhost:631/
fi

